// <auto-generated />
namespace PartiuAcademia.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1db));
        
        string IMigrationMetadata.Id
        {
            get { return "201504022105232_v1db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
